# -*- coding: utf-8 -*-
"""saikiran internship.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18tuEs67XMRPFa7XrvDoUjEf9NmGs8EZB
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_csv("SampleSuperstore.csv")
df.head()

print(df["Ship Mode"].unique())
print(df["Segment"].unique())
print(df["Country"].unique())
print(df["Category"].unique())

df.describe()

df.info()

df.isna().sum()

df.groupby("Region") ["Sales"].sum().plot.bar()

df.groupby("Region") ["Profit"].sum().plot.bar()

df.groupby("Region") ["Sales"].sum().plot.pie(autopct="%1.0f%%")

df.groupby("Region") ["Profit"].sum().plot.pie(autopct="%1.0f%%")

df.groupby("Segment") ["Sales"].sum().plot.bar()

df.groupby("Category") ["Sales"].sum().plot.pie(autopct="%1.0f%%")

df.groupby("State") ["Sales"].sum().plot.bar()

